[dev]
  targetPort = 8083
[build]
  command = "npm run build"
  publish = "_site"
[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/script.exclusions.js"
  status = 200
[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  
[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[[edge_functions]]
function = "style-management"
path = "/style/"

[[plugins]]
  package = "netlify-plugin-mastodon-alias"

  [plugins.inputs]
    username = "gingerchew"
    instance = "queer.party"
    strictUsername = "ginger"