[build]
  command = "npm run build"
  publish = "_site"

[[plugins]]
  package = "netlify-plugin-mastodon-alias"

  [plugins.inputs]
    username = "gingerchew"
    instance = "queer.party"
    strictUsername = "ginger"